Added reset button when clicked reset all fields .
abdelhalimjean/entreprises pull request #32
Opened 2024-05-30 12:25 UTC by eljily

2024-05-30 12:26 UTC, eljily commented
close #24

2024-05-30 12:30 UTC, abdelhalimjean requested changes

2024-05-30 12:30 UTC, abdelhalimjean commented on package.json
> +    "primeicons": "^7.0.0",
```suggestion

```
we're using @ng-icons/bootstrap-icons, no need for other icons library
https://ng-icons.github.io/ng-icons/#/browse-icons

2024-06-01 16:44 UTC, abdelhalimjean requested changes

2024-06-01 16:44 UTC, abdelhalimjean commented on package-lock.json
> +        "primeicons": "^7.0.0",
remove

2024-06-01 17:02 UTC, abdelhalimjean approved these changes

2024-06-01 17:08 UTC, merged